POST http://localhost:3000/register/
Content-Type: application/json

{
    "username":"akhil",
    "email":"akhil558@gmail.com",
    "password":"akhil123"
}

###
POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"suresh",
    "password":"suresh123"
}

###

GET http://localhost:3000/users/
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.c3VyZXNo.NgxXIrGR8ySH558OwOfSrvV081agL3Kfmx7Fky4Ppuk

###
DELETE http://localhost:3000/delete/